# Generated by Django 3.0.8 on 2020-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='star',
            new_name='rating',
        ),
    ]
